# Generated by Django 4.0.2 on 2022-02-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initiation_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
