# Generated by Django 4.0.2 on 2022-02-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_auth', '0002_user_initiation_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_related_name': 'user', 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
