# Generated by Django 4.0.2 on 2022-02-12 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='committee_head', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='committee_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.committee'),
        ),
    ]
