# Generated by Django 4.0.2 on 2022-02-12 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_alter_committee_head_alter_committee_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='task_assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
