# Generated by Django 4.0.2 on 2022-02-18 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0005_alter_committee_head_alter_task_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low Priority'), (2, 'Normal Priority'), (3, 'High Priority')], default=2),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Idea'), (2, 'Open'), (3, 'To Do'), (4, 'In Progress'), (5, 'Review'), (6, 'Completed')], default=2),
        ),
        migrations.AlterField(
            model_name='committee',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='head_committee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='committee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_task', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='portal.committee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
